name: Orquestrador - Deploy Completo do Projeto

on:
  workflow_dispatch:

jobs:
  deploy-backends:
    name: Deploy Microserviços Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ ms-product, ms-payment-methods, ms-seller, ms-review ]
    steps:
      - name: Disparar Deploy ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: MercadoLibre-case/${{ matrix.repo }}
          event-type: deploy
          client-payload: '{"ref": "main"}'
